### ISSUE TITLE
Auth Error

### ISSUE THREAD

**Issue by mcconnellt150** [gsroberts/atlassian-cloud-backup-tool#1]
Hi,

I seem to be getting the below error when trying to run

31/05/2018 10:21:22 [Atlassian-Backup-Service] Beginning backup for JIRA...
31/05/2018 10:21:22 [Atlassian-Backup-Service] Attempting to log in to Atlassian...
31/05/2018 10:21:23 [Atlassian-Backup-Service] Failed to authenticate to Atlassian cloud servers!
31/05/2018 10:21:23 [Atlassian-Backup-Service] Aborting backup job for JIRA!

I'm guessing its to do with how they moved to ID (they seemed to have changed the URLs to track and initiate downloads, is there and updates version yet :)

Thanks

**Comment by gsroberts** [comment]
Howdy.

Assuming you are attempting to backup a cloud instance of Jira, could you please check that the following are true in your appsettings.json file:

-  You are using the subdomain for the cloud instance in the `cloudAccount` field (the xxxx in https://xxxx.atlassian.net from the URL you use to access to the JIRA cloud instance)

-  You are using the JIRA profile username, not email address, for your JIRA account in the `userName` field of the appsettings.json file.  This can be found on your profile page for your JIRA account

-  You are using the password associated with your JIRA profile in the `password` field of the appsettings.json file

-  The JIRA profile you are attempting to use needs to be at least an administrator on the cloud instance

Please let me know if you still are unable to authenticate after checking those items.

**Comment by gsroberts** [comment]
For illustrative purposes, your `appsettings.config` file should look like this:

```
{
    "cloudAccount": "mycompany",
    "userName": "gsroberts",
    "password": "mysupersecretandhorriblylongJIRApassword",
    "jiraBackupConfig": {
        "destination": "/vault/Backups/Jira",
        "fileName": "jira-backup-{0}.zip",
        "backupsToKeep": 7,
        "maxAgeArchivedBackups": 30
    },
    "confluenceBackupConfig": {
        "destination": "/vault/Backups/Confluence",
        "fileName": "confluence-backup-{0}.zip",
        "backupsToKeep": 7,
        "maxAgeArchivedBackups": 30
    },
    "bitbucketBackupConfig": {
        "backupRepoWikis": true,
        "destination": "/vault/Backups/BitBucket",
        "password": "mysupersecretandhorriblylongBITBUCKETpassword",
        "teamName": "myawesometeam",
        "user": "gsroberts@mycompany.com",
        "userName": "gsroberts",
        "useTeam": true
    }
}
```

**Comment by mcconnellt150** [comment]
Perfect, I was creating a file called appsettings.config and putting those details in, didn't realise that I should have been using the appsettings.json instead xD

**Comment by gsroberts** [comment]
Awesome.  Glad it helped.  I really should update the README to be a little clearer on the subject of the `appsettings.json` file.  

If I don't hear back from you in the next day or so I'll mark this issue as completed.  :)
