### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by mcconnellt150** [gsroberts/atlassian-cloud-backup-tool#2]
I assume they've changed how to authenticate and it has broken this, is there any way you could fix this or provide a workaround?

**Comment by gsroberts** [comment]
It might be a couple of days before I can get to it but I will take a look.  Might be something that can be quickly fixed.

Do you have an error message you can share by any chance?

**Comment by mcconnellt150** [comment]
Sure

19/11/2019 16:23:01 [Atlassian-Backup-Service] Beginning backup for Confluence...
19/11/2019 16:23:01 [Atlassian-Backup-Service] Attempting to log in to Atlassian...
19/11/2019 16:23:02 [Atlassian-Backup-Service] Failed to authenticate to Atlassian cloud servers!
19/11/2019 16:23:02 [Atlassian-Backup-Service] Aborting backup job for Confluence!
19/11/2019 16:23:02 [Atlassian-Backup-Service] Beginning backup for JIRA...
19/11/2019 16:23:02 [Atlassian-Backup-Service] Attempting to log in to Atlassian...
19/11/2019 16:23:02 [Atlassian-Backup-Service] Failed to authenticate to Atlassian cloud servers!
19/11/2019 16:23:02 [Atlassian-Backup-Service] Aborting backup job for JIRA!

I think you're only allowed to use API keys as your token now instead of passwords
https://confluence.atlassian.com/cloud/api-tokens-938839638.html

And thanks

**Comment by gsroberts** [comment]
Awesome, thanks.  I will take a look as soon as I am able and let you know
what I find.

**Comment by gsroberts** [comment]
@mcconnellt150 I'm going to reach out on the Atlassian JIRA instance and see if I can get an answer but it looks live they may have unpublished the `/rest/obm` endpoints in their API, either intentionally or otherwise.  Appears to have happened around Oct 18th of this year.

Without those endpoints, there is not a way to trigger a backup or get status and download information, effectively rendering this tool and any script/tool derived from the scripts that Atlassian provided (all use the `obm` endoints) useless.

I'll update here when and if I get an answer.

**Comment by gsroberts** [comment]
Actually, disregard my last.  They moved the endpoints to a different path.  The new endpoints do rely on the basic auth using email and token as you mentioned so thanks for that heads up.  I'm working on a fix now.

**Comment by mcconnellt150** [comment]
Awesome, thanks for looking over it all

**Comment by gsroberts** [comment]
I've just published a new release that should address the issue and I've updated the README as well.

When you update your existing install be sure to include the changes to the `appsettings.json` file.

Please let me know if you experience any issues with the new package.  I will wait to close this issue until you've confirmed your backups are functioning again.

**Comment by mcconnellt150** [comment]
Hi There,

Jira seems to be sorted now but Confluence still has that error

25/11/2019 16:48:30 [Atlassian-Backup-Service] Beginning backup for Confluence...
25/11/2019 16:48:30 [Atlassian-Backup-Service] Attempting to log in to Atlassian...
25/11/2019 16:48:30 [Atlassian-Backup-Service] Failed to authenticate to Atlassian cloud servers!
25/11/2019 16:48:30 [Atlassian-Backup-Service] Aborting backup job for Confluence!
25/11/2019 16:48:30 [Atlassian-Backup-Service] Beginning backup for JIRA...
25/11/2019 16:48:30 [Atlassian-Backup-Service] Triggering backup...
25/11/2019 16:48:30 [Atlassian-Backup-Service] Failed to trigger backup generation! Reason : {"error":"Backup frequency is limited. You cannot make another backup right now. Approximate time until next allowed backup: 47h 47m"}
25/11/2019 16:48:30 [Atlassian-Backup-Service] Attempting to obtain last task ID for this JIRA instance...
25/11/2019 16:48:30 [Atlassian-Backup-Service] Success!
25/11/2019 16:48:30 [Atlassian-Backup-Service] Backup Task ID => 38303
25/11/2019 16:48:30 [Atlassian-Backup-Service] Success ==> 100
25/11/2019 16:48:30 [Atlassian-Backup-Service] Backup file generation complete.
25/11/2019 16:48:35 [Atlassian-Backup-Service] Getting generated backup file from https://mysite.atlassian.net/plugins/servlet/export/download/export/download/?fileId=bddfab197a41
25/11/2019 16:48:36 [Atlassian-Backup-Service] Downloading 755370549 bytes of data...
25/11/2019 16:49:09 [Atlassian-Backup-Service] Download complete.
25/11/2019 16:49:09 [Atlassian-Backup-Service] Backup complete.
25/11/2019 16:49:09 [Backup-Tool] Cleaning up archived backups located at /jira

**Comment by gsroberts** [comment]
Oh, I see the problem.  Sorry about that.

It might take me a day or two to get around to it and I don't have a Confluence instance to test against anymore so I might have to do a bug-fix release and have you verify it corrects the issue.  Does that sound good?

**Comment by mcconnellt150** [comment]
Sounds good buddy

**Comment by gsroberts** [comment]
Ok, I've made the change and pushed the bugfix release.

Please grab it at your earliest convenience and let me know if it corrects the issue.

**Comment by mcconnellt150** [comment]
All sorted now, thanks for taking the time to fix :)

**Comment by gsroberts** [comment]
Awesome.  Glad to hear!

I'll go ahead and close this issue then.

Thanks for your help resolving the issue.
