### ISSUE TITLE
Upgrade .net core

### ISSUE THREAD

**Issue by mcconnellt150** [gsroberts/atlassian-cloud-backup-tool#3]
Are you able to upgrade the .net core version for this app?

**Comment by gsroberts** [comment]
That's should be relatively simple/straight-forward as far as I'm aware.  The only difficulty I will have in doing so is I no longer have access to an Atlassian cloud instance as an admin so testing those changes may be an issue.

**Comment by gsroberts** [comment]
@mcconnellt150 I've just pushed a new release which is strictly an upgrade to .NET 6, no functionality changes at all.  Feel free to give it a shot and see if that works for you.  As previously mentioned, I currently don't have a way to test the code against a live cloud instance but none of that functionality has changed so - at least in theory - the application should no have any issues doing what it did before the upgrade.

https://github.com/gsroberts/atlassian-cloud-backup-tool/releases/tag/v1.1

**Comment by mcconnellt150** [comment]
Working perfectly, thank you for taking time to update it :)

**Comment by tecxx** [comment]
thanks for the tool - a little gem, very much appreciated.
i compiled it to a self-contained exe, and even that works flawlessly

![image](https://user-images.githubusercontent.com/4305825/195045634-7b7fc430-5bfd-48ba-9d07-e815ddb3e7d3.png)

cheers!

ps: your readme mentions the filename "appsettings.config" but it only worked as ".json"

**Comment by gsroberts** [comment]
Excellent! Thanks for letting me know. :)
